# Generated by Django 3.1.3 on 2021-06-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Resume', models.FileField(upload_to='Resume/')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
