# Generated by Django 3.2 on 2021-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210613_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='Resume',
            new_name='resume',
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
