# Generated by Django 3.2 on 2021-06-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_resume_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.CharField(default='Error', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='Error', max_length=20),
            preserve_default=False,
        ),
    ]
